# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_federation_articles_contacts_docx_in_federation_inst_korpus_instructor_news_referee_regions_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_federation',
            options={'verbose_name': 'О_федерации'},
        ),
    ]
