# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180104_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='autor',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='docx',
            options={'verbose_name': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='in_federation',
            options={'verbose_name': 'В_федерацию'},
        ),
        migrations.AlterModelOptions(
            name='inst_korpus',
            options={'verbose_name': 'Инструкторский корпус'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Инструкторы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'verbose_name': 'Судьи'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='rukovodstvo',
            options={'verbose_name': 'Руководство'},
        ),
        migrations.AlterModelOptions(
            name='sud_corpus',
            options={'verbose_name': 'Судейский корпус'},
        ),
        migrations.AlterModelOptions(
            name='turnirs',
            options={'verbose_name': 'Турниры'},
        ),
        migrations.AlterModelOptions(
            name='turnirs_result',
            options={'verbose_name': 'Результаты турниров'},
        ),
        migrations.AlterModelOptions(
            name='uch_corpus',
            options={'verbose_name': 'Учебный корпус'},
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
